/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Aluno
 */
public class Pizzaria extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Pizzaria.class.getName());

    /**
     * Creates new form Pizzaria
     */
    public Pizzaria() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jButtonSelect = new javax.swing.JButton();
        jCheckBox4queijos = new javax.swing.JCheckBox();
        jCheckBoxCalabresa = new javax.swing.JCheckBox();
        jCheckBoxMarguerita = new javax.swing.JCheckBox();
        jCheckBoxBacon = new javax.swing.JCheckBox();
        jCheckBoxFileMignon = new javax.swing.JCheckBox();
        jCheckBoxFrango = new javax.swing.JCheckBox();
        jCheckBoxPortuguesa = new javax.swing.JCheckBox();
        jCheckBoxStrognoff = new javax.swing.JCheckBox();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextAreaSaboresSelecionados = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Sabores"));

        jButtonSelect.setText("Selecionar");
        jButtonSelect.addActionListener(this::jButtonSelectActionPerformed);

        jCheckBox4queijos.setText("4 Queijos");
        jCheckBox4queijos.addActionListener(this::jCheckBox4queijosActionPerformed);

        jCheckBoxCalabresa.setText("Calabresa");

        jCheckBoxMarguerita.setText("Marguerita");

        jCheckBoxBacon.setText("Bacon");

        jCheckBoxFileMignon.setText("Filé MIgnon");

        jCheckBoxFrango.setText("Frango c/Requeijão");

        jCheckBoxPortuguesa.setText("Portuguesa");

        jCheckBoxStrognoff.setText("Strognoff");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButtonSelect)
                .addGap(299, 299, 299))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(221, 221, 221)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jCheckBox4queijos)
                    .addComponent(jCheckBoxCalabresa)
                    .addComponent(jCheckBoxMarguerita)
                    .addComponent(jCheckBoxBacon))
                .addGap(60, 60, 60)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jCheckBoxStrognoff)
                    .addComponent(jCheckBoxPortuguesa)
                    .addComponent(jCheckBoxFrango)
                    .addComponent(jCheckBoxFileMignon))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jCheckBox4queijos)
                    .addComponent(jCheckBoxFileMignon))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jCheckBoxCalabresa)
                    .addComponent(jCheckBoxFrango))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jCheckBoxPortuguesa)
                    .addComponent(jCheckBoxMarguerita, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jCheckBoxBacon)
                    .addComponent(jCheckBoxStrognoff))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 29, Short.MAX_VALUE)
                .addComponent(jButtonSelect)
                .addContainerGap())
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Sabores selecionados"));

        jTextAreaSaboresSelecionados.setEditable(false);
        jTextAreaSaboresSelecionados.setBackground(new java.awt.Color(255, 153, 255));
        jTextAreaSaboresSelecionados.setColumns(20);
        jTextAreaSaboresSelecionados.setRows(5);
        jScrollPane1.setViewportView(jTextAreaSaboresSelecionados);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 641, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(21, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 138, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(58, 58, 58)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(34, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 34, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonSelectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSelectActionPerformed
        jTextAreaSaboresSelecionados.setText("");
        if (jCheckBox4queijos.isSelected()) {
            jTextAreaSaboresSelecionados.append(jCheckBox4queijos.getText() + "\n");
        }
        if (jCheckBoxCalabresa.isSelected()) {
            jTextAreaSaboresSelecionados.append(jCheckBoxCalabresa.getText() + "\n");
        }
        if (jCheckBoxMarguerita.isSelected()) {
            jTextAreaSaboresSelecionados.append(jCheckBoxMarguerita.getText() + "\n");
        }
        if (jCheckBoxBacon.isSelected()) {
            jTextAreaSaboresSelecionados.append(jCheckBoxBacon.getText() + "\n");
        }
        if (jCheckBoxFileMignon.isSelected()) {
            jTextAreaSaboresSelecionados.append(jCheckBoxFileMignon.getText() + "\n");
        }
        if (jCheckBoxFrango.isSelected()) {
            jTextAreaSaboresSelecionados.append(jCheckBoxFrango.getText() + "\n");
        }
        if (jCheckBoxPortuguesa.isSelected()) {
            jTextAreaSaboresSelecionados.append(jCheckBoxPortuguesa.getText() + "\n");
        }
        if (jCheckBoxStrognoff.isSelected()) {
            jTextAreaSaboresSelecionados.append(jCheckBoxStrognoff.getText() + "\n");
        }
    }//GEN-LAST:event_jButtonSelectActionPerformed

    private void jCheckBox4queijosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox4queijosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBox4queijosActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Pizzaria().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonSelect;
    private javax.swing.JCheckBox jCheckBox4queijos;
    private javax.swing.JCheckBox jCheckBoxBacon;
    private javax.swing.JCheckBox jCheckBoxCalabresa;
    private javax.swing.JCheckBox jCheckBoxFileMignon;
    private javax.swing.JCheckBox jCheckBoxFrango;
    private javax.swing.JCheckBox jCheckBoxMarguerita;
    private javax.swing.JCheckBox jCheckBoxPortuguesa;
    private javax.swing.JCheckBox jCheckBoxStrognoff;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextAreaSaboresSelecionados;
    // End of variables declaration//GEN-END:variables
}
